name: "All Tests: Safari (stable)"

# We never interact with the GitHub API, thus we can simply disable all
# permissions the GitHub token would have.
permissions: {}

on:
  push:
    branches:
      - epochs/daily
      - triggers/safari_stable

env:
  safaridriver_diagnose: false

jobs:
  results_safari:
    name: "All Tests: Safari (stable)"
    runs-on:
      - self-hosted
      - webkit-ews
    timeout-minutes: 180
    strategy:
      matrix:
        current-chunk: [1, 2, 3, 4, 5, 6, 7, 8]
        total-chunks: [8]
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.0
        fetch-depth: 1
      - name: Enable safaridriver diagnostics
        if: env.safaridriver_diagnose == true
        run: |-
          rm -rf ~/Library/Logs/com.apple.WebDriver/
          defaults write com.apple.WebDriver DiagnosticsEnabled 1
      - name: Enable safaridriver
        run: |-
          set -eux -o pipefail
          export SYSTEM_VERSION_COMPAT=0
          sudo safaridriver --enable
          defaults write com.apple.Safari WebKitJavaScriptCanOpenWindowsAutomatically 1
      - name: Update hosts
        run: |-
          set -eux -o pipefail
          ./wpt make-hosts-file | sudo tee -a /etc/hosts
      - name: Update manifest
        run: ./wpt manifest
      - name: Run tests
        run: |-
          set -eux -o pipefail
          export SYSTEM_VERSION_COMPAT=0
          ./wpt run \
            --no-manifest-update \
            --no-restart-on-unexpected \
            --no-fail-on-unexpected \
            --this-chunk=${{ matrix.current-chunk }} \
            --total-chunks=${{ matrix.total-chunks }} \
            --chunk-type hash \
            --log-wptreport ${{ runner.temp }}/wpt_report_${{ matrix.current-chunk }}.json \
            --log-wptscreenshot ${{ runner.temp }}/wpt_screenshot_${{ matrix.current-chunk }}.txt \
            --log-mach - \
            --log-mach-level info \
            --channel stable \
            --kill-safari \
            --max-restarts 100 \
            safari \
            infrastructure
      - name: Publish results
        uses: actions/upload-artifact@v4.1.0
        with:
          name: safari-results
          path: |
            ${{ runner.temp }}/wpt_report_*.json
            ${{ runner.temp }}/wpt_screenshot_*.txt
          if-no-files-found: "error"
      - name: Publish safaridriver logs
        if: env.safaridriver_diagnose == true
        uses: actions/upload-artifact@v4.1.0
        with:
          name: safaridriver-logs
          path: ~/Library/Logs/com.apple.WebDriver/
          if-no-files-found: warn
      - name: Cleanup
        if: always()
        run: |-
            set -ux
            sudo sed -i '' '/^# Start web-platform-tests hosts$/,/^# End web-platform-tests hosts$/d' /etc/hosts
